language:
  ruby

rvm:
  - 2.1
  - 2.2
  - 2.3

matrix:
  fast_finish:
    true

notifications:
  email: false

install: true

before_script:
  - bundle install

script:
  - bundle exec rake spec

gemfile:
  - Gemfile
